parameters:
  - name: projectname
    type: string
  - name: sqlProjectPath
    type: string
    default: 'sqlproject_azure_dedicated_dp/sqlproject_azure_dedicated_dp.sqlproj'
    displayName: 'Path to SQL Database Project file'
  - name: AzureRMServiceConnection
    type: string
  - name: environmentName
    type: string
  - name: serverName
    type: string
  - name: databaseName
    type: string
  - name: buildConfiguration
    type: string
    default: 'Release'
    displayName: 'Build Configuration (Debug or Release)'
    values:
      - Debug
      - Release
  - name: artifactName
    type: string
    default: 'dacpac-package'
    displayName: 'Pipeline Artifact Name'
  - name: pool
    type: string
    default: 'Default'
    displayName: 'Agent Pool'

steps:

- task: DownloadPipelineArtifact@2
  displayName: 'Download DACPAC Artifact'
  inputs:
    artifactName: '${{ parameters.artifactName }}'
    targetPath: '$(Pipeline.Workspace)/dacpac'

- task: SqlAzureDacpacDeployment@1
  displayName: "Create compare script(s)"
  inputs:
    azureSubscription: ${{ parameters.AzureRMServiceConnection }}
    AuthenticationType: servicePrincipal
    ServerName: ${{ parameters.serverName }}
    DatabaseName: ${{ parameters.databaseName }}
    DeploymentAction: Script
    DacpacFile: '$(Pipeline.Workspace)/dacpac/${{ parameters.projectname }}.dacpac'

- task: CopyFiles@2
  displayName: "Copy ${{ parameters.environmentName }} Compare Script"
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)
    Contents: '**/GeneratedOutputFiles/${{ parameters.databaseName }}_Script.sql'
    TargetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: drop"
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: "${{ parameters.environmentName }}_compare_script"
