parameters:
  - name: environmentName
    type: string
  - name: serviceName
    type: string
  - name: locationCode
    type: string

jobs:
  - deployment: deploy_${{ parameters.serviceName }}_${{ parameters.locationCode }}_${{ parameters.environmentName }}_changes
    variables:
      - template: ../variables/${{ parameters.environmentName }}.job.vars.yml
    pool:
      name: Default
      vmImage: 'windows-latest'

    environment: "synapsesql_${{ parameters.environmentName }}"
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../tasks/deploy_sql_build_task.yml
              parameters:
                projectName: ${{ variables.projectName }}
                AzureRMServiceConnection: ${{ variables.AzureRMServiceConnection }}
                environmentName: ${{ parameters.environmentName }}
                serverName: ${{ variables.serverName }}
                databaseName: ${{ variables.databaseName }}
