/*Copy to History before truncate reloading -- do not delete this block of code*/
Declare @EffectiveFromMainControl datetime
Set @EffectiveFromMainControl = getdate()
Declare @EffectiveToMainControl datetime
set @EffectiveToMainControl=cast('2999-12-31' as datetime)

Update [ELT].[MainControlHistory]

set EffectiveTo=@EffectiveFromMainControl
where EffectiveTo =@EffectiveToMainControl

INSERT 
[ELT].[MainControlHistory]
(
[ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], 
[SourceTableSchemaName], 
[SourceTableName], [SourceQuery], 
[SourceQueryWhereClause], [WaterMarkQuery], 
[WaterMarkValue], [IncrementalClauseQuery],
[TargetSystemType], [TargetTableSchemaName], 
[TargetTableName], [TargetEntityPath], 
[StoredProcName], [IncrementalLoad], 
[IndexRebuildFactor], [IsActive], 
[SourceColumnDelimiter], [FirstRowAsHeader],
[PostScriptProcedure], 
[WaterMarkDataType]
,EffectiveFrom,EffectiveTo)

Select  
[ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], 
[SourceTableSchemaName], 
[SourceTableName], [SourceQuery], 
[SourceQueryWhereClause], [WaterMarkQuery], 
[WaterMarkValue], [IncrementalClauseQuery],
[TargetSystemType], [TargetTableSchemaName], 
[TargetTableName], [TargetEntityPath], 
[StoredProcName], [IncrementalLoad], 
[IndexRebuildFactor], [IsActive], 
[SourceColumnDelimiter], [FirstRowAsHeader],
[PostScriptProcedure], 
[WaterMarkDataType],
@EffectiveFromMainControl as EffectiveFrom, @EffectiveToMainControl as EffectiveTo from   [ELT].[MainControl]

Truncate Table   [ELT].[MainControl]

/*Copy to History before truncate reloading  -- do not delete this block of code*/

INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (47, N'ControlIQ', N'API', N'CSService', NULL, N'PlanData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CSService_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (1, N'ControlIQ', N'API', N'MOPS', NULL, N'StaffAdminDataV2', N'https://odata-api.workwareplus.com/westpac/odata/StaffAdminDataV2/Get(workgroupId=220,groupId=1,includeUnassignedUsers=true)', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_MOPS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (35, N'ControlIQ', N'API', N'LS', NULL, N'PlanData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_LS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (25, N'ControlIQ', N'API', N'NZOPS', NULL, N'StaffAdminDataV2', N'', N'', NULL, N'2023-10-01', NULL, N'SQL', N'Landing', N'ControlIQ_NZOPS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 0, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (15, N'ControlIQ', N'API', N'CS', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (43, N'ControlIQ', N'API', N'CSService', NULL, N'StaffAdminDataV2', N'', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_CSService_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (17, N'ControlIQ', N'API', N'CS', NULL, N'PlanData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (45, N'ControlIQ', N'API', N'CSService', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CSService_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (75, N'ControlIQ', N'API', N'NZTS', NULL, N'NotesAndCommentsData', N'https://odata-api.workwareplus.com/westpac/odata/NotesAndCommentsData/GetRangeV2(workgroupId=2535,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[11002,11019])', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZTS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (34, N'ControlIQ', N'API', N'LS', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_LS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (38, N'ControlIQ', N'API', N'EBS', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_EBS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (53, N'ControlIQ', N'API', N'EBS', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_EBS_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (30, N'ControlIQ', N'API', N'NZOPS', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2023-10-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZOPS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 0, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (60, N'COP', N'ADLS', NULL, N'dbo', N'coptransactions', N'SELECT [PartitionKey]
					,[RowKey]
					,[Timestamp]
					,[transactionId]
					,[account]
					,[direction]
					,[type]
					,[payload]
			FROM dbo.coptransactions', NULL, N'SELECT ISNULL(MAX([Timestamp]),''{WaterMarkValue}''),''DateTime''  from COP.Transactions', N'1999-12-31 23:59:59.000001', N'Timestamp gt datetime''{WaterMarkValue}''', N'SQL', N'Landing', N'cop_coptransactions', NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (32, N'ControlIQ', N'API', N'LS', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_LS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (26, N'ControlIQ', N'API', N'NZOPS', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2023-10-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZOPS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 0, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (20, N'ControlIQ', N'API', N'NZIO', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZIO_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (52, N'ControlIQ', N'API', N'LS', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_LS_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (33, N'ControlIQ', N'API', N'LS', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_LS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (41, N'ControlIQ', N'API', N'EBS', NULL, N'PlanData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_EBS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (78, N'ControlIQ', N'API', N'NZTS', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZTS_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (28, N'ControlIQ', N'API', N'NZOPS', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2023-10-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZOPS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 0, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (64, N'NZDW_ODSP', N'SQL', NULL, N'Landing', N'S_CARDS_ATPT_SPEC_TXNS_H', N'SELECT * FROM Landing.S_CARDS_ATPT_SPEC_TXNS_H', NULL, NULL, NULL, NULL, N'NZDW_ODSP', N'NZDW', N'S_CARDS_ATPT_SPEC_TXNS_H', NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (29, N'ControlIQ', N'API', N'NZOPS', NULL, N'PlanData', N'', N'', NULL, N'2023-10-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZOPS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 0, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (69, N'ControlIQ', N'API', N'NZKYCS', NULL, N'PlanData', N'https://odata-api.workwareplus.com/westpac/odata/PlanData/GetRangeV2(workgroupId=2513,groupId=1,rangeType=''Custom'',{IncrementalClause},planUnitId=1)', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZKYCS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (21, N'ControlIQ', N'API', N'NZIO', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZIO_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (44, N'ControlIQ', N'API', N'CSService', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CSService_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (24, N'ControlIQ', N'API', N'NZIO', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZIO_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (36, N'ControlIQ', N'API', N'LS', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_LS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (50, N'ControlIQ', N'API', N'CC', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CC_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (7, N'ControlIQ', N'API', N'CC', NULL, N'StaffAdminDataV2', N'', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_CC_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (62, N'NZDW_ODSP', N'SQL', NULL, N'Landing', N'S_NZLO_LND_APPL_EXTRACT', N'SELECT * FROM Landing.S_NZLO_LND_APPL_EXTRACT', NULL, NULL, NULL, NULL, N'NZDW_ODSP', N'NZDW', N'S_NZLO_LND_APPL_EXTRACT', NULL, NULL, 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (8, N'ControlIQ', N'API', N'CC', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CC_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (59, N'NZDW_ODSP', N'Oracle', NULL, N'DWSTAGE', N'S_NZLO_LND_APPL_EXTRACT', N'SELECT DATE_KEY, LENDING_APPLICATION_NUMBER, LND_APPL_CREATED_DATE, CHANNEL, CREDIT_RESPONSE_DESCRIPTION, CREDIT_RESPONSE_CREATED_DATE, LND_APPL_STATUS_CREATED_DATE, LND_APPL_STATUS_DESCRIPTION, LA_BROKER_DETAIL_ID, LAST_INSERT_JOB_KEY FROM DWSTAGE.S_NZLO_LND_APPL_EXTRACT_C_H ', N'', N'SELECT ISNULL(MAX([LAST_INSERT_JOB_KEY]),''{WaterMarkValue}''),''BIGINT''  from NZDW.S_NZLO_LND_APPL_EXTRACT ', N'-9999999999999', N' LAST_INSERT_JOB_KEY > ''{WaterMarkValue}''', N'SQL', N'Landing', N'S_NZLO_LND_APPL_EXTRACT', NULL, N'[ODSP].[LoadNZL_LAND_APPLICATIONS_Extract]', 1, NULL, 1, NULL, NULL, NULL, N'BIGINT')
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (40, N'ControlIQ', N'API', N'EBS', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_EBS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (3, N'ControlIQ', N'API', N'MOPS', NULL, N'CoreTaskVolumeV2', N'https://odata-api.workwareplus.com/westpac/odata/CoreTaskVolumeV2/GetRangeV2(workgroupId=220,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[2371])', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_MOPS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (51, N'ControlIQ', N'API', N'NZIO', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZIO_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (12, N'ControlIQ', N'API', N'CC', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CC_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (71, N'ControlIQ', N'API', N'NZKYCS', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2023-10-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZKYCS_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (48, N'ControlIQ', N'API', N'CSService', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CSService_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (66, N'ControlIQ', N'API', N'NZKYCS', NULL, N'WorkgroupProductionDataV2', N'https://odata-api.workwareplus.com/westpac/odata/WorkgroupProductionDataV2/GetRangeV3(workgroupId=2513,groupId=1,rangeType=''Custom'',{IncrementalClause},category=null,additionalDataTypes=[''StaffReferenceId''],onlyVerifiedData=0)', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZKYCS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (49, N'ControlIQ', N'API', N'CSService', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CSService_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (11, N'ControlIQ', N'API', N'CC', NULL, N'PlanData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CC_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (27, N'ControlIQ', N'API', N'NZOPS', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2023-10-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZOPS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 0, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (4, N'ControlIQ', N'API', N'MOPS', NULL, N'NotesAndCommentsData', N'https://odata-api.workwareplus.com/westpac/odata/NotesAndCommentsData/GetRangeV2(workgroupId=220,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[2371])', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_MOPS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (18, N'ControlIQ', N'API', N'CS', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (46, N'ControlIQ', N'API', N'CSService', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CSService_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (42, N'ControlIQ', N'API', N'EBS', NULL, N'RTMStaffMemberActivityData', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_EBS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (39, N'ControlIQ', N'API', N'EBS', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_EBS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (77, N'ControlIQ', N'API', N'NZTS', NULL, N'RTMStaffMemberActivityData', N'https://odata-api.workwareplus.com/westpac/odata/RTMStaffMemberActivityData/GetRangeV3(workgroupId=2535,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[11002,11019])', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZTS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (76, N'ControlIQ', N'API', N'NZTS', NULL, N'PlanData', N'https://odata-api.workwareplus.com/westpac/odata/PlanData/GetRangeV2(workgroupId=2535,groupId=1,rangeType=''Custom'',{IncrementalClause},planUnitId=1)', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZTS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (5, N'ControlIQ', N'API', N'MOPS', NULL, N'PlanData', N'https://odata-api.workwareplus.com/westpac/odata/PlanData/GetRangeV2(workgroupId=220,groupId=1,rangeType=''Custom'',{IncrementalClause},planUnitId=1)', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_MOPS_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (2, N'ControlIQ', N'API', N'MOPS', NULL, N'WorkgroupProductionDataV2', N'https://odata-api.workwareplus.com/westpac/odata/WorkgroupProductionDataV2/GetRangeV3(workgroupId=220,groupId=1,rangeType=''Custom'',{IncrementalClause},category=null,additionalDataTypes=[''StaffReferenceId''],onlyVerifiedData=0)', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_MOPS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (61, N'COP', N'SQL', NULL, N'ODSReporting', N'Cop_Transactions', N'SELECT [PartitionKey]
					  ,[RowKey]
					  ,[Timestamp]
					  ,[transactionId]
					  ,[account]
					  ,[direction]
					  ,[type]
					  ,[schemeName]
					  ,[identification]
					  ,[nv_schemeName]
					  ,[nv_accountType]
					  ,[nv_name]
					  ,[nv_identification]
					  ,[accountType]
					  ,[accountStatus]
					  ,[verificationMatched]
					  ,[verificationMatchedReasonCode]
					  ,[accountNamesRaw]
					  ,[ErrorCode]
					  ,[ErrorMessage]
					  ,[Errors]
					  ,[payload]
					  ,getdate() as ODSLastUpdated
					  ,''{PipelineID}'' as ODSPipelineID
				  FROM [ODSReporting].[Cop_Transactions]', NULL, NULL, NULL, NULL, N'SQL', N'COP', N'Transactions', NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (63, N'NZDW_ODSP', N'Oracle', NULL, N'DWSTAGE', N'S_CARDS_ATPT_SPEC_TXNS_H', N'SELECT DATE_KEY,ORG_CODE,LOGO,ACT_NBR,MT_REF_NBR,MT_DESC,POST_DT,TXN_DT,TXN_CODE,POSTING_TYPE_DESCRIPTION,POSTING_AMT,DR_CR_IND,CUSTOMER_NO,CUSTOMER_NAME,GL_ACCOUNT,GL_PRODUCT,GL_COST_CENTRE,STAFF_ID,LAST_INSERT_JOB_KEY FROM DWSTAGE.S_CARDS_ATPT_SPEC_TXNS_H', N'', N'SELECT ISNULL(MAX([LAST_INSERT_JOB_KEY]),''{WaterMarkValue}''),''BIGINT''  from NZDW.S_CARDS_ATPT_SPEC_TXNS_H ', N'-9999999999999', N' LAST_INSERT_JOB_KEY > ''{WaterMarkValue}''', N'SQL', N'Landing', N'S_CARDS_ATPT_SPEC_TXNS_H', NULL, NULL, 1, NULL, 1, NULL, NULL, NULL, N'BIGINT')
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (65, N'ControlIQ', N'API', N'NZKYCS', NULL, N'StaffAdminDataV2', N'https://odata-api.workwareplus.com/westpac/odata/StaffAdminDataV2/Get(workgroupId=2513,groupId=1,includeUnassignedUsers=true)', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_NZKYCS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (16, N'ControlIQ', N'API', N'CS', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (19, N'ControlIQ', N'API', N'NZIO', NULL, N'StaffAdminDataV2', N'', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_NZIO_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (31, N'ControlIQ', N'API', N'LS', NULL, N'StaffAdminDataV2', N'', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_LS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (13, N'ControlIQ', N'API', N'CS', NULL, N'StaffAdminDataV2', N'', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_CS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (23, N'ControlIQ', N'API', N'NZIO', NULL, N'PlanData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZIO_PlanData', NULL, N'ControlIQ.LoadPlanData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (9, N'ControlIQ', N'API', N'CC', NULL, N'CoreTaskVolumeV2', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CC_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (22, N'ControlIQ', N'API', N'NZIO', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZIO_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (37, N'ControlIQ', N'API', N'EBS', NULL, N'StaffAdminDataV2', N'', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_EBS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (54, N'ControlIQ', N'API', N'MOPS', NULL, N'WorkgroupProductionDataIncludingWorkLocation', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_MOPS_WorkgroupProductionDataIncludingWorkLocation', NULL, N'[ControlIQ].[LoadWorkgroupProductionDataIncludingWorkLocation]', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (72, N'ControlIQ', N'API', N'NZTS', NULL, N'StaffAdminDataV2', N'https://odata-api.workwareplus.com/westpac/odata/StaffAdminDataV2/Get(workgroupId=2535,groupId=1,includeUnassignedUsers=true)', N'', NULL, NULL, NULL, N'SQL', N'Landing', N'ControlIQ_NZTS_StaffAdminDataV2', NULL, N'ControlIQ.LoadStaffAdminDataV2', 0, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (6, N'ControlIQ', N'API', N'MOPS', NULL, N'RTMStaffMemberActivityData', N'https://odata-api.workwareplus.com/westpac/odata/RTMStaffMemberActivityData/GetRangeV3(workgroupId=220,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[2371])', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_MOPS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (70, N'ControlIQ', N'API', N'NZKYCS', NULL, N'RTMStaffMemberActivityData', N'https://odata-api.workwareplus.com/westpac/odata/RTMStaffMemberActivityData/GetRangeV3(workgroupId=2513,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[10659])', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZKYCS_RTMStaffMemberActivityData', NULL, N'ControlIQ.LoadRTMStaffMemberActivityData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (67, N'ControlIQ', N'API', N'NZKYCS', NULL, N'CoreTaskVolumeV2', N'https://odata-api.workwareplus.com/westpac/odata/CoreTaskVolumeV2/GetRangeV2(workgroupId=2513,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[10659])', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZKYCS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (10, N'ControlIQ', N'API', N'CC', NULL, N'NotesAndCommentsData', N'', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CC_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (14, N'ControlIQ', N'API', N'CS', NULL, N'WorkgroupProductionDataV2', N'', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_CS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (74, N'ControlIQ', N'API', N'NZTS', NULL, N'CoreTaskVolumeV2', N'https://odata-api.workwareplus.com/westpac/odata/CoreTaskVolumeV2/GetRangeV2(workgroupId=2535,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[11002,11019])', N'', NULL, N'2025-09-02', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZTS_CoreTaskVolumeV2', NULL, N'ControlIQ.LoadCoreTaskVolumeV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (68, N'ControlIQ', N'API', N'NZKYCS', NULL, N'NotesAndCommentsData', N'https://odata-api.workwareplus.com/westpac/odata/NotesAndCommentsData/GetRangeV2(workgroupId=2513,groupId=1,rangeType=''Custom'',{IncrementalClause},hierarchyIds=[10659])', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZKYCS_NotesAndCommentsData', NULL, N'ControlIQ.LoadNotesAndCommentsData', 1, NULL, 1, NULL, NULL, NULL, NULL)
INSERT [ELT].[MainControl] ([ELTControlID], [SourceSystem], [SourceSystemType], [SourceEntityPath], [SourceTableSchemaName], [SourceTableName], [SourceQuery], [SourceQueryWhereClause], [WaterMarkQuery], [WaterMarkValue], [IncrementalClauseQuery], [TargetSystemType], [TargetTableSchemaName], [TargetTableName], [TargetEntityPath], [StoredProcName], [IncrementalLoad], [IndexRebuildFactor], [IsActive], [SourceColumnDelimiter], [FirstRowAsHeader], [PostScriptProcedure], [WaterMarkDataType]) VALUES (73, N'ControlIQ', N'API', N'NZTS', NULL, N'WorkgroupProductionDataV2', N'https://odata-api.workwareplus.com/westpac/odata/WorkgroupProductionDataV2/GetRangeV3(workgroupId=2535,groupId=1,rangeType=''Custom'',{IncrementalClause},category=null,additionalDataTypes=[''StaffReferenceId''],onlyVerifiedData=0)', N'', NULL, N'2025-09-01', N'startDate={startDate},endDate={endDate}', N'SQL', N'Landing', N'ControlIQ_NZTS_WorkgroupProductionDataV2', NULL, N'ControlIQ.LoadWorkgroupProductionDataV2', 1, NULL, 1, NULL, NULL, NULL, NULL)
